import { Property } from './types';

export const sampleProperties: Property[] = [
  {
    id: '1',
    title: '파주시 월롱면 계획관리 토지 1,200평',
    type: '토지',
    dealType: '매매',
    price: 180000,
    areaSqm: 3967,
    address: '경기도 파주시 월롱면 위전리 산 123-4',
    region: '경기',
    landCategory: '임야',
    zoning: '계획관리',
    roadFrontage: '6m 포장도로 접면',
    shape: '부정형',
    terrain: '평지',
    description: '파주시 월롱면에 위치한 계획관리지역 토지입니다. 6m 포장도로에 접해 있으며, 평탄한 지형으로 공장 및 창고 부지로 적합합니다. 월롱IC와 인접하여 입지 조건이 우수합니다.',
    images: [],
    createdAt: '2026-02-15',
  },
  {
    id: '2',
    title: '파주시 탄현면 신축 공장 800평 매매',
    type: '공장',
    dealType: '매매',
    price: 320000,
    areaSqm: 2645,
    address: '경기도 파주시 탄현면 법흥리 456-7',
    region: '경기',
    landCategory: '공장용지',
    zoning: '일반공업',
    roadFrontage: '12m 포장도로 접면',
    shape: '정방형',
    terrain: '평지',
    description: '파주시 탄현면 국가산업단지 인근 신축 공장입니다. 건축면적 500평, 토지 800평으로 넓은 야적장 확보 가능합니다. 천장고 9m, 전기용량 300kW 완비.',
    images: [],
    createdAt: '2026-02-10',
  },
  {
    id: '3',
    title: '파주시 조리읍 대로변 창고 500평 임대',
    type: '창고',
    dealType: '임대',
    price: 5000,
    monthlyRent: 450,
    areaSqm: 1653,
    address: '경기도 파주시 조리읍 대능리 789-1',
    region: '경기',
    landCategory: '창고용지',
    zoning: '계획관리',
    roadFrontage: '8m 포장도로 접면',
    shape: '장방형',
    terrain: '평지',
    description: '파주시 조리읍 대로변에 위치한 창고입니다. 상온 창고 500평, 천장고 7m. 대형차량 진입 및 회차가 용이하며 물류 거점으로 최적의 장소입니다.',
    images: [],
    createdAt: '2026-02-12',
  },
];
