import { Property } from './types';

export const sampleProperties: Property[] = [
  {
    id: '1',
    title: '화성시 팔탄면 계획관리 토지 1,200평',
    type: '토지',
    dealType: '매매',
    price: 180000,
    areaSqm: 3967,
    address: '경기도 화성시 팔탄면 구장리 산 123-4',
    region: '경기',
    landCategory: '임야',
    zoning: '계획관리',
    roadFrontage: '6m 포장도로 접면',
    shape: '부정형',
    terrain: '평지',
    description: '화성시 팔탄면에 위치한 계획관리지역 토지입니다. 6m 포장도로에 접해 있으며, 평탄한 지형으로 공장 및 창고 부지로 적합합니다. 주변에 산업단지가 형성되어 있어 접근성이 우수합니다.',
    images: [],
    createdAt: '2026-02-15',
  },
  {
    id: '2',
    title: '안성시 일반공업 공장 800평 매매',
    type: '공장',
    dealType: '매매',
    price: 320000,
    areaSqm: 2645,
    address: '경기도 안성시 미양면 보체리 456-7',
    region: '경기',
    landCategory: '공장용지',
    zoning: '일반공업',
    roadFrontage: '12m 포장도로 접면',
    shape: '정방형',
    terrain: '평지',
    description: '안성시 일반공업지역 내 공장입니다. 건축면적 500평, 토지 800평으로 넓은 야적장 확보 가능합니다. 천장고 8m, 전기용량 200kW, 3상 전력 완비.',
    images: [],
    createdAt: '2026-02-10',
  },
  {
    id: '3',
    title: '이천시 준공업 창고 500평 임대',
    type: '창고',
    dealType: '임대',
    price: 5000,
    monthlyRent: 350,
    areaSqm: 1653,
    address: '경기도 이천시 부발읍 신원리 789-1',
    region: '경기',
    landCategory: '창고용지',
    zoning: '준공업',
    roadFrontage: '8m 포장도로 접면',
    shape: '장방형',
    terrain: '평지',
    description: '이천시 부발읍 준공업지역 창고입니다. 상온 창고 500평, 천장고 6m. 대형차량 회차 가능한 넓은 진입로. 이천IC에서 10분 거리로 물류 접근성 탁월.',
    images: [],
    createdAt: '2026-02-12',
  },
  {
    id: '4',
    title: '평택시 자연녹지 토지 2,000평',
    type: '토지',
    dealType: '매매',
    price: 400000,
    areaSqm: 6612,
    address: '경기도 평택시 청북읍 율북리 234-5',
    region: '경기',
    landCategory: '전',
    zoning: '자연녹지',
    roadFrontage: '4m 비포장도로 접면',
    shape: '부정형',
    terrain: '완경사',
    description: '평택시 청북읍 자연녹지 토지 2,000평입니다. 삼성전자 평택캠퍼스 인근으로 향후 개발 기대가 높은 지역. 현재 농지로 사용 중이며 전원주택 및 근린생활시설 가능.',
    images: [],
    createdAt: '2026-02-08',
  },
  {
    id: '5',
    title: '용인시 준공업 공장 1,500평 매매',
    type: '공장',
    dealType: '매매',
    price: 750000,
    areaSqm: 4959,
    address: '경기도 용인시 처인구 남사면 아곡리 567-8',
    region: '경기',
    landCategory: '공장용지',
    zoning: '준공업',
    roadFrontage: '15m 포장도로 접면',
    shape: '정방형',
    terrain: '평지',
    description: '용인시 남사면 준공업지역 대형 공장입니다. 토지 1,500평, 건물 1,000평. 사무동 별도, 식당 및 기숙사 완비. 경부고속도로 양재IC 30분, 영동고속도로 마성IC 15분.',
    images: [],
    createdAt: '2026-02-05',
  },
  {
    id: '6',
    title: '김포시 계획관리 창고 300평 임대',
    type: '창고',
    dealType: '임대',
    price: 3000,
    monthlyRent: 250,
    areaSqm: 992,
    address: '경기도 김포시 대곶면 대명리 890-2',
    region: '경기',
    landCategory: '창고용지',
    zoning: '계획관리',
    roadFrontage: '6m 포장도로 접면',
    shape: '장방형',
    terrain: '평지',
    description: '김포시 대곶면 계획관리지역 창고입니다. 300평 상온 창고, 천장고 5.5m. 소규모 물류센터로 적합하며, 김포공항 및 인천공항 접근성 우수.',
    images: [],
    createdAt: '2026-02-18',
  },
];
